Allow variable length columns to be fetched through unbuffered prepared statements
viaduck/mariadbpp pull request #46
Opened 2021-10-31 11:54 UTC by mrmurnst

The result set implementation for prepared statements currently assumes the `mysql_stmt_fetch` to either succeed or fail completely. There is, however, the case of truncated results (return code `MYSQL_DATA_TRUNCATED`) if one or more of the binding buffers were too small.

In such a case, the buffers should be resized and the respective columns should be fetched again, as [the MySQL documentation for `mysql-stmt-fetch`](https://dev.mysql.com/doc/c-api/8.0/en/mysql-stmt-fetch.html) suggests.
I've added the corresponding code - let me know what you think.

For performance reasons, one could also resize the buffers exponentially to avoid repeated resizes by small amounts, but I've kept it simple in the first step...

2021-11-02 21:43 UTC, roussosalex requested changes
Thanks for contributing. Could you add a test case for a truncated statement result?

2021-11-03 16:59 UTC, mrmurnst commented
There are currently no tests at all for unbuffered queries with `account::set_store_result(false)`.
I therefore just made the existing test suite parameterized to execute it once with buffered queries (as it is now) and once with unbuffered queries. This also causes my fix above to be used in `ParameterizedQueryTest::bindAnyDatatype` and `ParameterizedQueryTest::bindReuseString`.

That's a lot of small changes in a lot of files, though. I'd rather make another pull request with those...

2021-11-03 17:19 UTC, mrmurnst commented
Done. It's here: #47 .

2021-11-16 21:45 UTC, roussosalex approved these changes

2021-11-16 21:46 UTC, merged